name: Deploy MarkBind site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install dependencies for BE
      - name: Install backend dependencies
        run: npm install

      # Install dependencies for FE
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # List the contents of the directory to check the structure
      - name: Check directory contents
        run: |
          echo "Listing contents of /home/runner/work/cs4218-project-2024-team07/cs4218-project-2024-team07"
          ls -R /home/runner/work/cs4218-project-2024-team07/cs4218-project-2024-team07
          echo "Listing contents of /home/runner/work/cs4218-project-2024-team07"
          ls -R /home/runner/work/cs4218-project-2024-team07


      # Install additional Babel dependencies needed for Jest
      - name: Install Babel for Jest
        run: |
          npm install --save-dev @babel/core @babel/preset-env babel-jest

      # Create a Jest configuration with Babel on the fly
      - name: Create Jest Config
        run: |
          echo 'module.exports = {' > jest.config.js
          echo '  transform: {' >> jest.config.js
          echo '    "^.+\\\\.[t|j]sx?$": "babel-jest"' >> jest.config.js
          echo '  },' >> jest.config.js
          echo '  transformIgnorePatterns: [' >> jest.config.js
          echo '    "/node_modules/(?!bson)"' >> jest.config.js
          echo '  ]' >> jest.config.js
          echo '};' >> jest.config.js

      # Create Babel configuration on the fly
      - name: Create Babel Config
        run: |
          echo '{ "presets": ["@babel/preset-env"] }' > .babelrc

      # Run tests for FE
      - name: Run tests for FE
        run: npm run test:frontend

      # Run tests for BE with environment variables
      - name: Run tests for BE
        env:
          PORT: 6060
          DEV_MODE: development
          MONGO_URL: mongodb+srv://hongsheng:hongsheng123@cs4218-test-cluster.vvmcw.mongodb.net/
          JWT_SECRET: HGFHGEAD12124322432
          BRAINTREE_MERCHANT_ID: hmrc3kfrt2xrvtvp
          BRAINTREE_PUBLIC_KEY: d3rnqcjwn7zk4fpt
          BRAINTREE_PRIVATE_KEY: 767ed9ddd903781349d4c2af441f8eaa
          NODE_ENV: test
        run: npm run test:backend

      # Install MarkBind globally
      - name: Install MarkBind
        run: npm install -g markbind-cli

      # Build MarkBind site
      - name: Build MarkBind site
        run: |
          cd client
          markbind build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/_site
